application: osqa-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:
- url: /media
  static_dir: media

- url: /favicon.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: main.application

libraries:
  - name: django
    version: 1.4